name: Deploy backend

on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: ./backend

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run e2e tests
        run: npm run test:e2e
        env:
          JWT_SECRET: "test"
          OUR_ENV: "dev"

  deploy:
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build and push
        uses: "./.github/templates/build-and-push"
        with:
          context: ./backend
          file: ./backend/Dockerfile
          dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
          image-name: ${{ secrets.DOCKER_IMAGE_NAME }}
      - name: Deploy
        uses: "./.github/templates/deploy-backend-container"
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          server-port: 3002
          application-port: 3002
          image-name: ${{ secrets.DOCKER_IMAGE_NAME }}
          container-name: secretly-backend
          jwt-secret: ${{ secrets.JWT_SECRET }}
          our-env: prod
          mongo-url: ${{ secrets.MONGO_URL }}

          google-client-id: ${{ secrets.GOOGLE_CLIENT_ID }}
          google-client-secret: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          google-redirect-uri: ${{ secrets.GOOGLE_REDIRECT_URI }}
          google-redirect-uri-alternative: ${{ secrets.GOOGLE_REDIRECT_URI_ALTERNATIVE }}

          gh-client-id: ${{ secrets.GH_CLIENT_ID }}
          gh-client-secret: ${{ secrets.GH_CLIENT_SECRET }}
          gh-client-id-alternative: ${{ secrets.GH_CLIENT_ID_ALTERNATIVE }}
          gh-client-secret-alternative: ${{ secrets.GH_CLIENT_SECRET_ALTERNATIVE }}
          gh-cryptly-app-id: ${{ secrets.GH_CRYPTLY_APP_ID }}
          gh-cryptly-app-private-key: ${{ secrets.GH_CRYPTLY_APP_PRIVATE_KEY }}
          gh-webhooks-secret: ${{ secrets.GH_WEBHOOKS_SECRET }}

          logdash-api-key: ${{ secrets.LOGDASH_API_KEY }}

          posthog-api-key: ${{ secrets.POSTHOG_API_KEY }}
          posthog-host: ${{ secrets.POSTHOG_HOST }}
      - name: Prune
        uses: "./.github/templates/prune"
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
